#!/bin/bash

#/ NAME
#/     list pingdom -- list active pingdom probes
#/
#/ SYNOPSIS
#/     list pingdom

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

readonly URL_PINGDOM="https://my.pingdom.com/probes/feed"

# entry point
function main {
 curl -s "$URL_PINGDOM" | perl -ne 'map { print "$_\n" } m{(\d+(?:\.\d+){3}).*?Active}' | sort
}

require sub "$BASH_SOURCE" "$@"
